steps:
  # Build/install the mvn project
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
  # Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/github.com/zippoobbiz/gcp-streaming-tweets-pubsub-java:$SHORT_SHA', '.']
  # Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/github.com/zippoobbiz/gcp-streaming-tweets-pubsub-java:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['get', 'po']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=australia-southeast1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'
- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'bash'
  args: 
  - '-c' 
  - 'kubectl create secret generic twitter-stream-secret --from-literal=TWKEYWORDS=big,query,Bigquery,BigQuery --from-literal=TWBATCHSIZE=5 --from-literal=TWLANGUAGE=en --from-literal=TWPROJECTID=phil-xu-sandpit --from-literal=PUBSUB_TOPIC=twittstopic --from-literal=ACCESSTOKEN=$$ACCESSTOKEN --from-literal=ACCESSTOKENSEC=$$ACCESSTOKENSEC --from-literal=CONSUMERKEY=$$CONSUMERKEY --from-literal=CONSUMERSECRET=$$CONSUMERSECRET --from-literal=TWSTREAMMODE=publisher  || exit 0'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=australia-southeast1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'
  secretEnv: ['ACCESSTOKEN', 'ACCESSTOKENSEC', 'CONSUMERKEY', 'CONSUMERSECRET']
- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'bash'
  args: 
  - '-c' 
  - 'echo $$CREDENTIALS > temp.json && kubectl create secret generic twitter-stream-credential --from-file=temp.json  || exit 0'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=australia-southeast1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'
  secretEnv: ['CREDENTIALS']
  
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'kubernetes/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=australia-southeast1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'
#step 4
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
   'set', 
   'image', 
   'deployment', 
   'gcp-streaming-tweets-pubsub-java-deployment', 
   'gcp-streaming-tweets-pubsub-java=gcr.io/$PROJECT_ID/github.com/zippoobbiz/gcp-streaming-tweets-pubsub-java:$SHORT_SHA'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=australia-southeast1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'
- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    kubectl expose deploy gcp-streaming-tweets-pubsub-java-deployment --port=9000 --target-port=9000 --type=LoadBalancer || exit 0
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=australia-southeast1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'
images: 
- 'gcr.io/$PROJECT_ID/github.com/zippoobbiz/gcp-streaming-tweets-pubsub-java:$SHORT_SHA'
secrets:
- kmsKeyName: projects/phil-xu-sandpit/locations/global/keyRings/phil-xu-sandpit-key-ring/cryptoKeys/phil-xu-sandpit-key
  secretEnv:
    ACCESSTOKEN: CiQAhOAvUnPLy3KBgQPs0zNq6vLVFIZwo1ko8LyaW4nmzMvHqB8SWwA6MbhPv7e9qOsD8ydsplJgP1hzEjAstj6hvmrD5PEASyFD7JcSTW9+K9oGJtg+a+nJbYmi4DP5h7emlAq8ko2WdQJtWMrss/ZRGLkcwNhtK3PJiDbcRVPCAyc=
    ACCESSTOKENSEC: CiQAhOAvUkMc/igc5O3SKDoqrWkNyqCs9vsHwWzcR9SiYk2CkR8SVgA6MbhP9PHHk54R1cisK+WZbQhFnNEtEUvMqxgyBUR0NyQ6ZluNSDejEFOGFWGNcXtZkODMh5bgNs8qHKlOWwEuJ+0HuTosOxHZSAwNOXV5g/vHvNIk
    CONSUMERKEY: CiQAhOAvUng9cevb2MebDIjsQJc7ZFFeLk15oJ6qcNqHrJ8PriQSPgA6MbhPgL3jDXPV93zw6zg1F1nf3sihG1slDMQAlBoOt62dUHpKQC4F5gorIEH7GCxn/OAdNi9EYHq/oUq5
    CONSUMERSECRET: CiQAhOAvUoirKcVtKCOsCmmCC/Y8x9JTOj53+BvHZyxj6LefWI8SVAA6MbhPLlL6+PoIcr4feTSsssbJIKd5ne4lWvRiXOzh8qmowLENM58fuCnqVetlQ4e3EE6rFwVlr/j2ncnbmaE1c/9Q7qGAL6mxvnry5RoDF3AQcg==
    CREDENTIALS: CiQAhOAvUqCjdeNGN+N0fQG0L+jLhTinBcKTLtwDBXxHuchUAskSthIAOjG4T+TkhICG88Tsv3zxQycPI7XE50Cq0VTBe4+4EQHhINFUjC7EROY2PvazSnlqfRA9dt3RB6N6+kKzDR8+1sZRYi480UU35KZ7+cfgismoBwg0519pwfZkwmVXbra1x2x8A3rdMs8kDO7fxa1lf0zV57/7RDFPeJ6XudjZfflqu1fYeD7P6afTUY1at3JZML2P94aUpQsPxqewKxeLR5TG56WnDitXn+XpNyAZ7PKLvbxJ2jsV4ytJK+nGLXcgQUipuvTtDRvPKK/XWDJzhmL9SuuDdJJYgc5kZFVq/mo4On2XJF4DxeWg3IgdJac6hEtxYkY4S6POobUqBLBEAN8IuNU5S+5N2d4BBE62IhJ1Szk2Ycv+lvXrY6HXU0T1ht/mma7qOl7Z1NveQzzju22HE6Jur1X73CcFbgWLtZKR1slyVGwSUfouJvRlsLxvElrab2uvy+NMpz+iorq6/5Q3AhR9dRgV5Pizwhq4itt4eTNa6QUkAbLomfoEvrpGq5cJK5294hYaykpH4hTWWdwLxC0kDKKj+GxElM4VOLyrOptlk4Q4Vony3MnLryfA7E25NjAr6+jQmcjCc1rXBCVHSjm/G0NXgVml5coZSBWFOeGzqaJHbGe3oC2AtZpPUZpstJPqIy4bewfuRibez89wo9xA3QmRAjoYrW2i66tKDRPxBtGwAC4UlC+nnQwiAL1yrlVixT6qoKTqyuum/rIoIsFc/yCjhGJ4vqo8/roOJLOKyG71FMUV8xtyJD3BC2ejSEvNr1vIt+dY+6W/IxhOgzHBgeVnQtewfyqDcM85ZpAWUEYmMyLpxkczllDItJ7+KyiZ+BM4szKZlZTfgSDHUCDUHbXSaBC4vGe/t/oHi4JXuvUFPJTM16+uN5v50EytBw4hjdBKPJAXm9WmLQv4QtSthR8iNxzqs3Ip4fiD7QgNeQ9K7zxBzFsWP9yISoh9s93pAj2Xra03ci/Qfsuu4I+qR2VJRlXErT2CUYvmv8aPf4nLsju6lxqHtHJRzFZhZcx9d9E+H8LvZww+1FlzSfJWHCBoLgnWhyt64E210koE0oYZnsp9/vtrNSDLzfTkLOECo1F738kmRQJERUFtjTvwCcmXPK89sD1Nn3vHN1gfQSuTLWf1a1BfCfoYEjPHUxtxuMJfXb+AFqJYmT/ceLaH7RB3YoMsr2hZ5sUX5NXb4FvGorcE5sdJfHL65GLBySZOGxz2O4cyqjV9huxfDzbPRu+9EinhqmlDn/zjzq6iVNv9Gu8TRNJandc+w5DqWMoJxXdD/SvhmHjFziGAPEklgOwn66apzk5fTmUVFn8IP1Ek2JQZKRHw9274Yv+bb18EVMBumQdIwRUhylNFRO75OBVkC292FLCFQhAUnvefgBaJzGh7JZL99DBLcUWJ94oK5qVUkHgqLEQZaOZAw+JsjbjHUrNPBirQWyxbFvYydB28oCoWGJeaGJ2sgtOaqOm8/tBU2g+Gul95cJYOdhZ22O1Leiv3JVeioxj/qH7U2XjiMHUD7I1+J6HWr0IRQ3Tm9DRQQ04S6Fzvh0AjQTUViXQnLUquM78UiuvSwRIuTpjaoI1QtFo20lH3y5bgB6HZ+J6d03fO9e05wEXU5w73+w9UhlH1RNzL6gjm34olSzPZIv5HYN/lA0MbWSP2xdRdh1yE4YUwZLRB2o6+2lMbHRdFw0hr5uaY6E4r4d4Qi/x+HyBo+Y4UvFW08gtoDIO2wsmvLqYObCzZVWt1nymnPy+lZ4ZaFhcJm2236b6q32w5epTKY+k0/WGyLfkAAL+mT+AFfCufUv4mY/ra05J4k0OTqAWnl/rWaNdS9DTvHBEiYfo87jyYUHkWruxuMDDgRnV7E6WrSON9bQtgAM28E8/u7Q/sdAQhCPDGlSY1WkJvbxan+FUGK7ONckwxzH3d0p7OSjXENoFPJpgLS0tAH4pk8N9jl4wmvcSRXY1Ay1YpYLjiD3pA1gcbg0pszQQcibneHq7v+/seci/h1PmmqzY16zyKNiY7raxY/Mj+dpbjFZnINWboGX18K5LumIqCwPegkk2qYOKZIEngvyZHndgECW3sYCBuxBrN111c/tcEof6jm87Uz465JIC5JB1TW4KtXOWGeXmOfrDVy2r/U7cSWJVUW+HQ8qmDnzU/zqFGqiYX3JmOet6pJ2Mt8ZxAHHeUrpS1aG/GC8eo2IonapXzSFvZzZNSlA5vmXjltc/PrUZlfIavDHm4+QrULraSE9kZgcm3GFXYBRlCFhLANFAhmI9ZqUcBhVJNTC1D11yXX/KJhe/5fY5DP5wZ9xPrXWl01DbRNY0LFd8FjgF6u0TNhsJ7WEIJG1cAfM/VQQ6eAfq9BVII0IEmTIptzl/e3yxgis0ikIJ4opjlcc90mTvrWGMuVqKWWDbKAiAk64S1xN2D4v8tj8Tpe2W74aEimK35hO4WfGoqEi9UAp0+OvyTZYASFzjiZSBhQLSViBPA2XJ0x6t2m5K7GpVfEddY0WKfoTOf710mg1G7vJO/3RPaCB5BtL/4ukxZWKxTwgutNoJ9Poda3C8/Xid9vNZ1kdKxw5LulBBqzulBy6yO55Dlj/61/pOcA5RcYmuAEj2HkP5xI6SgES8sw+W9Rzdpsb8qauLPEPceveKyU+Y5ej/+480P4eqNO/80bVBS+m+WNsbDwKM7wCdFqefpG0aV/H8fAop66ehwYqd4Ka5RfOxAMsSZr4L91JciXHuilcm1+xCtVJT25j94wSDtaovV7L5zp9qINowS+EtN+sJZlmTQzXxv/3osp4+Y4Lj28oUQQJreyJ6MO57U/qRjUZYf31lsWUG84Yrgy/+B25Zo/31pUcyt5Ws1lVFQR6HGtDWiXr/R6lh14kowW+Ul+HRblzAPB4DdQhCdge7kXOnRUhipfOTLyCGBSwCx5rqwsE7s9sY8/s1V84+D+wyQQa2FKuKVpERT3SBJ1ZtnBZerRi937nKykiiMpadRlkZrK4qGWBXJfpi/VReYsaG5VLYEsziVIHqnhbsBNwnj+DpO96aZ71mlt0P8efzLWbvV+wVGJN/Yw7/NFT8hW2a/KlV+QAUBfjeBNp7AyQx8kUHAYWN66xNrjZ8ObOm3v50s+03klv6F4yAN7GgZHgIiGyQ=