steps:
  # Build/install the mvn project
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
  # Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/github.com/zippoobbiz/gcp-streaming-tweets-pubsub-java:$SHORT_SHA', '.']
  # Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/github.com/zippoobbiz/gcp-streaming-tweets-pubsub-java:$SHORT_SHA']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: 
  - 'beta'
  - 'run'
  - 'deploy'
  - 'gcp-streaming-tweets-pubsub-java'
  - '--image'
  - 'gcr.io/$PROJECT_ID/github.com/zippoobbiz/gcp-streaming-tweets-pubsub-java:$SHORT_SHA'
  - '--region'
  - 'asia-northeast1'
  - '--platform'
  - 'managed'
  - '--set-env-vars'
  - 'TWKEYWORDS="big query Bigquery BigQuery",TWBATCHSIZE=10,TWLANGUAGE=en,TWPROJECTID="phil-xu-sandpit",PUBSUB_TOPIC=twittstopic,ACCESSTOKEN=$ACCESSTOKEN'
  secretEnv: ['ACCESSTOKEN', 'ACCESSTOKENSEC', 'CONSUMERKEY', 'CONSUMERSECRET']
images: 
- 'gcr.io/$PROJECT_ID/github.com/zippoobbiz/gcp-streaming-tweets-pubsub-java:$SHORT_SHA'
secrets:
- kmsKeyName: projects/phil-xu-sandpit/locations/global/keyRings/phil-xu-sandpit-key-ring/cryptoKeys/phil-xu-sandpit-key
  secretEnv:
    ACCESSTOKEN: CiQAhOAvUnPLy3KBgQPs0zNq6vLVFIZwo1ko8LyaW4nmzMvHqB8SWwA6MbhPv7e9qOsD8ydsplJgP1hzEjAstj6hvmrD5PEASyFD7JcSTW9+K9oGJtg+a+nJbYmi4DP5h7emlAq8ko2WdQJtWMrss/ZRGLkcwNhtK3PJiDbcRVPCAyc=