steps:
  # Build/install the mvn project
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
  # Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/github.com/zippoobbiz/gcp-streaming-tweets-pubsub-java:$SHORT_SHA', '.']
  # Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/github.com/zippoobbiz/gcp-streaming-tweets-pubsub-java:$SHORT_SHA']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - --image=gcr.io/$PROJECT_ID/github.com/zippoobbiz/gcp-streaming-tweets-pubsub-java:$SHORT_SHA
  - --location=australia-southeast1-a	
  - --cluster=standard-cluster-1
- name: 'gcr.io/cloud-builders/kubectl'
  args: 
  - create
  - secret
  - generic
  - test-secret
  - --from-literal="TWKEYWORDS=big,query,Bigquery,BigQuery"
  - --from-literal="TWBATCHSIZE=5"
  - --from-literal="TWLANGUAGE=en"
  - --from-literal="TWPROJECTID=phil-xu-sandpit"
  - --from-literal="PUBSUB_TOPIC=twittstopic"
  - --from-literal="ACCESSTOKEN=$$ACCESSTOKEN"
  - --from-literal="ACCESSTOKENSEC=$$ACCESSTOKENSEC"
  - --from-literal="CONSUMERKEY=$$CONSUMERKEY"
  - --from-literal="CONSUMERSECRET=$$CONSUMERSECRET"
  secretEnv: ['ACCESSTOKEN', 'ACCESSTOKENSEC', 'CONSUMERKEY', 'CONSUMERSECRET']
images: 
- 'gcr.io/$PROJECT_ID/github.com/zippoobbiz/gcp-streaming-tweets-pubsub-java:$SHORT_SHA'
secrets:
- kmsKeyName: projects/phil-xu-sandpit/locations/global/keyRings/phil-xu-sandpit-key-ring/cryptoKeys/phil-xu-sandpit-key
  secretEnv:
    ACCESSTOKEN: CiQAhOAvUnPLy3KBgQPs0zNq6vLVFIZwo1ko8LyaW4nmzMvHqB8SWwA6MbhPv7e9qOsD8ydsplJgP1hzEjAstj6hvmrD5PEASyFD7JcSTW9+K9oGJtg+a+nJbYmi4DP5h7emlAq8ko2WdQJtWMrss/ZRGLkcwNhtK3PJiDbcRVPCAyc=
    ACCESSTOKENSEC: CiQAhOAvUkMc/igc5O3SKDoqrWkNyqCs9vsHwWzcR9SiYk2CkR8SVgA6MbhP9PHHk54R1cisK+WZbQhFnNEtEUvMqxgyBUR0NyQ6ZluNSDejEFOGFWGNcXtZkODMh5bgNs8qHKlOWwEuJ+0HuTosOxHZSAwNOXV5g/vHvNIk
    CONSUMERKEY: CiQAhOAvUng9cevb2MebDIjsQJc7ZFFeLk15oJ6qcNqHrJ8PriQSPgA6MbhPgL3jDXPV93zw6zg1F1nf3sihG1slDMQAlBoOt62dUHpKQC4F5gorIEH7GCxn/OAdNi9EYHq/oUq5
    CONSUMERSECRET: CiQAhOAvUoirKcVtKCOsCmmCC/Y8x9JTOj53+BvHZyxj6LefWI8SVAA6MbhPLlL6+PoIcr4feTSsssbJIKd5ne4lWvRiXOzh8qmowLENM58fuCnqVetlQ4e3EE6rFwVlr/j2ncnbmaE1c/9Q7qGAL6mxvnry5RoDF3AQcg==