FROM java:8

WORKDIR /

COPY pubsub-1.0-SNAPSHOT-jar-with-dependencies.jar publisher.jar
COPY Service_Account.json Service_Account.json

ENV PUBSUB_TOPIC={YOUR TOPIC}
ENV CONSUMERKEY={YOUR KEY}
ENV CONSUMERSECRET={YOUR KEY}
ENV ACCESSTOKEN={YOUR KEY}
ENV ACCESSTOKENSEC={YOUR KEY}
ENV TWSTREAMMODE=filter
ENV TWKEYWORDS={YOUR KEYWORDS}
ENV TWPROJECTID={YOUR PROJECT}
ENV GOOGLE_APPLICATION_CREDENTIALS=Service_Account.json

CMD ["java","-jar","publisher.jar"]