apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: twitter-stream
  labels:
    name: twitter-stream
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: twitter-stream
    spec:
      containers:
      - name: twitter-to-pubsub
        image: zippoobbiz/twitter-publisher:init
        env:
        - name: PROCESSINGSCRIPT
          value: twitter-to-pubsub
        # Change this to your pubsub topic
        - name: PUBSUB_TOPIC
          value: newtopic1
        # Change the following four settings to your twitter credentials
        # information.
        - name: CONSUMERKEY
          value: {YOUR KEY}
        - name: CONSUMERSECRET
          value: {YOUR KEY}
        - name: ACCESSTOKEN
          value: {YOUR KEY}
        - name: ACCESSTOKENSEC
          value: {YOUR KEY}
          # Change the mode to publisher if you want to send message to pubsub
        - name: TWSTREAMMODE
          value: publisher
          # Change this to your filtering keywords, separated with comma, no space
        - name: TWKEYWORDS
          value: your,key,words

