apiVersion: apps/v1 
kind: Deployment
metadata:
  name: gcp-streaming-tweets-pubsub-java-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      run: gcp-streaming-tweets-pubsub-java
  template:
    metadata:
      labels:
        run: gcp-streaming-tweets-pubsub-java
    spec:
      containers:
      - name: gcp-streaming-tweets-pubsub-java
        image: gcr.io/phil-xu-sandpit/github.com/zippoobbiz/gcp-streaming-tweets-pubsub-java:latest
       